### ISSUE TITLE
Add biome ID conflict check

### ISSUE THREAD

**Issue by chylex** [ganymedes01/TheErebus#244]
Check biome IDs used by Erebus before registering Erebus biomes, and in postinit to make sure they weren't replaced by another mod.

**Comment by chylex** [comment]
"Erebus biome IDs cannot be higher than 127!"
read plz

**Comment by Bogdan-G** [comment]
chylex, When you implement a number of more than 127?

**Comment by SMEZ1234** [comment]
You know that is how rare biomes work, right? Essentially, if a biome has an ID 128 more than an existing biome, then it may generate occasionally instead of that biome.
This is fine with most overworld biome adding mods, but having Erebus biomes trying to generate in the overworld would cause numerous issues.

I'm only assuming that this is the reason that Erebus biome IDs can't be more than 128. There are workarounds, involving messing with GenLayers, but when too many mods start changing them, stuff starts to go wrong.

Anyway, there are only 7 IDs that can't be set above 128. Just switch a few other IDs for these if you need to.

**Comment by Bogdan-G** [comment]
SMEZ1234, That's the problem when you put a lot of mods 255 is clearly on the limit or not enough. Can use subID if possible? (such as item)
Or add checks since openworld, although I generate biomes Erebus and they looked quite normal, but without a ceiling.

**Comment by SMEZ1234** [comment]
I'm not saying that you need to put all IDs above 128, just switch the Erebus' IDs for another mod's IDs that are above 128.

You could add checks if you had full control over the generation, but rare biome generation is badly handled and probably could do with a fix in Forge. Sub IDs don't exist, and it would be even more difficult to add them than it would be to extend the biome ID limit.

**Comment by Bogdan-G** [comment]
How much time has passed, even if you give ID biomes mod Erebus they normally work.

**Comment by ganymedes01** [comment]
From now on the mod will crash if the IDs are set to anything above 127 or something that is already taken.
It will also crash if another mod tries to replace an erebus biome.

**Comment by ganymedes01** [comment]
Also, next time please create a new issue if you want to report a crash
