### ISSUE TITLE
Many TESRs should be ISBRHs

### ISSUE THREAD

**Issue by purpleposeidon** [ganymedes01/TheErebus#280]
Easily fixed in 1.8 (I guess), but otherwise there's probably a couple of libs that'll take care of it in the mean time. If not, let me know if you need help with it.

**Comment by vadis365** [comment]
Will probably leave stuff as it is for the moment, but feel free to make a PR if you think it is necessary...
I don't know if it is really worth making stuff ISBR because the new json system will be a pain to convert to. Also not sure if development will continue in to 1.8 atm as we are a bit low on team members.

**Comment by Dylan4ever** [comment]
Purpleposeidon, is there any platform we can have a talk together perhaps? 

It's a bit of a necropost but I feel like this is a good way to reach you.

**Comment by purpleposeidon** [comment]
I (and, like, the rest of the Minecraft mod dev community, like, seriously)
can be reached at irc.esper.net (myself) as neptunepink on #factorization .
Here's an easy IRC client:
http://client00.chat.mibbit.com/?channel=%23factorization&server=irc.esper.net
, but a real IRC client is preferred. I'd rather not use skype. Could set
you up a #TheErebus channel and stuff.

**Comment by Dylan4ever** [comment]
I should've known, sorry, I am heavily disconnected from lots of community things after going on hiatus for half a year >.>.
