### ISSUE TITLE
Praying Manti shouldn't spawn in groups 

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#300]
Up the spawn rate but make only 1 spawn I suppose? They are solistic creatures by nature and all.

**Comment by vadis365** [comment]
Changing the spawn numbers won't work like that, it will still seem that they spawn in groups, because if a viable spawn area is found they will spawn. This would mean 2 blocks next to each other could be viable and it would look like a group. The only way to do it is make a specific rule in the mob to look for nearby mantises and not spawn if one is within a certain distance. I can do this at some point - but not for now. This issue is being closed for now. I may revisit it when I can be bothered.
