### ISSUE TITLE
some world blocks have unecessary extra metadata and some have split entities

### ISSUE THREAD

**Issue by trollworkout** [ganymedes01/TheErebus#351]
the metadata issue
for example marshwood 

in creative tab is
erebus:logMarshwood

but in the game some marshwood trees are actually made up of erebus:logMarshwood AND erebus:logMarshwood:3  (why use meta 3?)

all marshwood blocks when mined drop no meta version. ideally all blocks of one type should all be one type. i have a couple of entity/block scanners and they tell me a different story.

the split entities issue
for ex moss 
erebus:wallPlants goes from 0 (no meta) all the way to 7. although you only have 6 sides of the cube you have 8 types of moss entities. i understand you need moss entities for different facing sides but they should all be registered as one item. seems they are all different items if you have silk touch you can grab specific facing mosses that only work on certain surfaces. 

i can keep updating the list . is not very big but seems to be everpresent issue.

**Comment by vadis365** [comment]
The wall plants are coded in a specific way that all the metadata is necessary to be as it is.
I will disable silk touching for moss and mould in the next update as they can be sheared, which does give you the correct meta block ;) - I have myself made an automated mould farm, using TE, Minefactory Reloaded, Build Craft and Extra utilities that puts it in to the composter and makes compost which is then transported to a silo for the black ants to use. In the next release I will add a cultivated mould that spreads quicker to increase compost output.

The Marshwood was made like that because the roots were going to be used for something else that was never implemented. I will change that too - thanks.

**Comment by trollworkout** [comment]
no worries. is a great mod just a lot of fine tuning left to do i guess.

**Comment by trollworkout** [comment]
another 1 is the that coral glowing plant that spawns underwater but with a block of air around it and can't be planted underwater once removed. and is not even listed in the creative tab :)

**Comment by vadis365** [comment]
mostly done - coral is now a different issue :P
