### ISSUE TITLE
Erebus causes Thermal Dynamic's Creative Tab to crash

### ISSUE THREAD

**Issue by Kucan** [ganymedes01/TheErebus#356]
When Erebus is used along side Thermal Dynamics, attempting to view TD's Creative Tab will cause the client to crash with [the following error](http://pastebin.com/f5KQBEbY).

[A similar error been previously reported to the CofH team and KingLemming suggested that this was out of their hands.](https://github.com/CoFH/Feedback/issues/724)

Using process of elimination, it's apparent that Erebus is the cause.

The versions used are:

CoFHCore - 3.0.3-303
Thermal Foundation - 1.2.0-102
Thermal Expansion - 4.0.3B1-218
Thermal Dynamics - 1.1.0-161
The Erebus - 0.3a

**Comment by vadis365** [comment]
Hello,
Yes I can confirm this happens as I have also experienced it - Not just with The Erebus. I am also not sure as to what the cause is but I used KingLemming's suggestion and disabled Thermal Dynamic's creative tab in the config files. Using NEI will still allow you to access all the items and blocks.
Thanks For the report but I'm not sure it is actually our fault to fix.
Cheers,
Me.
