### ISSUE TITLE
Erebus Biomes STILL Generating in the Overworld, with IDs properly config'd

### ISSUE THREAD

**Issue by Zsashas** [ganymedes01/TheErebus#414]
![2015-11-04_23 20 55](https://cloud.githubusercontent.com/assets/6917535/10962280/e46d1678-834b-11e5-9916-996dddb63a61.png)

https://www.dropbox.com/s/f042txawzmml2wl/biome%28aligned%29.xlsx?dl=0

The dropbox link is the biome ID dump spreadsheet, because GitHub is being derpy and won't let me upload it directly.

**Comment by vadis365** [comment]
This is STILL not our fault - it is a biome ID conflict at your end.
The biome dumps that you provide will only show biomes that are registered NOT biomes that have overwritten other biomes. The only way to properly test this is remove all mods apart from the Erebus and NEI (for biome dumps), assign all Erebus biome ID's correctly (127 and below) and you will see that the biome ID's have mutations at ID+128. If this is still happening with only The Erebus loaded I will re-open the issue - but for now I am closing due to it being an isolated case.
