### ISSUE TITLE
Updates to 'tamed mobs'

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#417]
Umbergolem should follow owner.

Titan and Rhino Beetles should follow owner and there should be a way to make them stay in one spot - thinking of adding an item for this as right clicking is already being used. The item will put the beetle to sleep and maybe the beetles will emit 'zzzz' particles ;)

Tamed mobs should probably attack mobs AND players that attack the owner.

*Edit
Titan Beetles should have a Bamboo Crate version to go with the Chested and Ender-Chested.
A Petrified Chest version is not necessary as the the textures for them make me want to vomit. :P

**Comment by purpleposeidon** [comment]
That kinda sounds like it would break my titan beetle farm.

**Comment by vadis365** [comment]
Not if it was only applied to beetles that were wearing a riding kit I guess.

**Comment by vadis365** [comment]
@purpleposeidon - Sounds like you have been using the mod for a while. Would you share any screen shots of things you have set up? When the next update is out I want to post a few things from my server to show off some bits. People are not aware of lots of the features from the mod as our glorious mod owner ( @Dylan4ever .lazyteenager.com ) :P has never properly worked on the wiki or explained much to people via the forums.

**Comment by purpleposeidon** [comment]
Enh, not all that much. I did make ![the thing that I changed the portal code for](https://pbs.twimg.com/media/CS_ujDZUkAEDyTD.png:large), but you might notice I'm using Growthcraft bamboo instead of Erebus's. ;)


Some usage of umberstone: ![?](http://i.imgur.com/dRdYv1e.png)

And my austere bug farm: ![¿](http://i.imgur.com/wVqzDIt.jpg)

I'm not interested in ants, and haven't yet gotten started with the bees.

**Comment by vadis365** [comment]
Probably not worth doing bee stuff atm - I have to re-write the AI as it is a wee bit borked.

**Comment by vadis365** [comment]
Closing as using a lead will do for now.
