### ISSUE TITLE
Temple and Locust Frequency

### ISSUE THREAD

**Issue by Darkosto** [ganymedes01/TheErebus#482]
I'm not sure if Locust spawning has been addressed yet, however, upon testing it seems as though locusts are not spawning at all. Is there a possibility to increase their spawn rate?

Also, I've spent the last 20 minutes flying across a number of maps and cannot seem to find a single Temple in the Volcanic Desert Biome. I know they are spawning because Vadis shared a world Seed with one in it. Is there a possibility to increase their spawn rate, too? Or maybe a config option to turn it up?

Thank you!

**Comment by vadis365** [comment]
Locusts only spawn when Grasshoppers have bred a few times - they wander around and eat grass to do this and eventually turn in to a Locust. This has be made because if a player doesn't pay attention or Wasps are not around to kill the Grasshoppers you eventually end up with a load of 100hp Locusts in an area. I can ramp up the AI to work faster but I'm not to blame when you get ganked by 4 or 5 locusts in an area. An alternative would be to catch one and plant a load of vanilla tall grass/bonemeal grass blocks, let it eat the grass and multiply a few times and eventually one of them will mature in to a Locust.

The Temple spawn rate is quite low yes. I can add a config for testing out frequencies but if it is incorrectly balanced you may find more than one temple spawning in an area and messing up the gen.
