### ISSUE TITLE
Server Crash all time in erebus

### ISSUE THREAD

**Issue by m00nLP** [ganymedes01/TheErebus#561]
Hello, we have a big problem.
Every time we join the Erebus, our server crashes.

I have really no idea what I should still make.

I hope you can help me.
Here is the Chrash Report
https://www.file-upload.net/download-12332543/crash-2017-02-21_14.32.47-server.txt.html

**Comment by vadis365** [comment]
Hello,
I have looked at the crash report and there seems to be some problem between the generation of red gem blocks in the ulterior outback biome (would probably happen in other biomes too) because another mod is trying to 'tick' the blocks and force some sort of update. 

at mrtjp.core.world.BlockUpdateHandler$.onTick(blocktickhook.scala:79)
and 
MrTJPCore: Version: 1.1.0.33. Main class: mrtjp.core.handler.MrTJPCoreMod$. Source: MrTJPCore-1.1.0.33-universal.jar

show up in the log - I'm not exactly sure what it would be doing tbh. Is there any worldgen that can be blacklisted from the Erebus dimension (66 by default) in Mcjty's mod's?
Could you possibly report this to Mcjty as well? There may be some cross mod incompatibility going on and I know he's a really helpful guy - he may have some insight on the matter.
Cheers,
Me.

**Comment by vadis365** [comment]
Closing - 1.7.10 is no longer supported
