### ISSUE TITLE
antlion pyramid guardian drops burn

### ISSUE THREAD

**Issue by nateallen198** [ganymedes01/TheErebus#563]
it is possible for the ant lion idol guardian drops to fall in lava and burn, making the pyramid inaccessible. Consider making the 4 idol guardians respawn after some time, or have them place a chest on death rather than dropping entities.

**Comment by vadis365** [comment]
Hello,
This was thought about long ago and we decided that we would make items that spawn the idol guardians in the event of the scarabs being lost. If you have NEI (or some way of searching the items) you will find the items required that can be fully crafted in survival and will spawn the required Umbergolem Idol Guardian.
I know it's a pain - but the 1.7.10 version of The Erebus is no longer being updated, so that is your best bet ;)
Cheers,
Me.
