### ISSUE TITLE
Ores not picked up by Thaumcraft's native cluster system

### ISSUE THREAD

**Issue by Sunconure11** [ganymedes01/TheErebus#621]
Your ores are not being picked up by Thaumcraft for some reason, even though they should be.

**Comment by vadis365** [comment]
Bummer.
Erebus ores are Ore-dicted correct, as far as I remember, which is all I can really do.

**Comment by Sunconure11** [comment]
Maybe try and load them as early as possible? Thaumcraft likes to be first in many things, as I've found.

**Comment by vadis365** [comment]
No idea on this one, I don't use Thaumcraft and have no clue what 'native clusters' even involve.
Like I said Erebus ores are ore-dicted and registered using the forge events. If it's a load order thing or otherwise, it's something Thaumcraft is doing and not Erebus I guess. Closing as this is a low priority feature that isn't really this mods issue.

**Comment by Sunconure11** [comment]
Native clusters are basically a way to duplicate ores in Thaumcraft.

https://ftb.gamepedia.com/Native_Cluster_(Thaumcraft_4)
