### ISSUE TITLE
Water striders increadble super-speed in water

### ISSUE THREAD

**Issue by VioletWyvern** [ganymedes01/TheErebus#669]
When you equip with both sprint leggings and water striders,  And you sprint and jump into the water,  If you manage to landing just below the waterline, You will going extremely super-sonic fast,   This is wierd... 

This also happened when you in the shallow water,  When you standing at one block deep water and equipping sprint leggings and water striders and start running, this will also happened.

**Comment by vadis365** [comment]
![vbh7r](https://user-images.githubusercontent.com/6518708/50289866-f3322780-0461-11e9-892a-979bc5717aa6.png)
Hello,
Yes the sprint leggings have always done that, I never bothered adjusting for the water movement changes that MineCraft does. I have known about this since before the sprint leggings were even added to the mod but always thought it was amusing and never removed it. I may fix it one day ;)
Cheers,
Me.
