### ISSUE TITLE
Night vision [1.12.2 ]

### ISSUE THREAD

**Issue by raltus** [ganymedes01/TheErebus#688]
I am having a strobing issue when both this and Grimoire of Gaia are installed. I found the old issue from 2016 and linked it in the issue there, but thought I'd still mention it here since it applies to a later version. Normal night vision is fine, but when I use the ring from the mod the sky starts flashing.

**Comment by vadis365** [comment]
Hello,
This is something that is problematic, will look in to it again.
Thanks for the report,
Cheers,
Me.

**Comment by vadis365** [comment]
Hello,
I have moved the check to see if the goggles are worn, but I think this will still be an issue if you use both items at the same time as they probably both use the same effect.
Cheers,
Me.
*calling this fixed in dev - but if it still happens with the next Erebus update please open another issue.

**Comment by raltus** [comment]
Just tested and it's working properly now. I hadn't been using the goggles when I noticed the issue so I made sure to check it with both goggles and the ring as well as separate.
