### ISSUE TITLE
Block of bones won’t disable

### ISSUE THREAD

**Issue by astra-midnight** [ganymedes01/TheErebus#756]
I have tomb many graves installed and tried to disable the block of bones thing that spawns when you die but it doesn’t want to disable even though I changed it to off in the mod config and I have to remove the Erebus mod to get Tomb Many Graves to work. It’s a shame because I really look forward to trying this mod out.

**Comment by pimalel233** [comment]
Edit: I guess I have had false positive, after more testing it seems like Tombstone took over and spawned only theirs grave. I have no idea what I changed in the meantime.*

I'll add to that, ability to totally disable the bones or some kinf of integration between mods would be cool, as currently it just looks weird -> http://prntscr.com/qjcc64 - shows Erebus' bones and Corail Tombstone's tombstone (replaced the one it created because I used it already, but it spawned at the same place)

**Comment by ghost** [comment]
About this, i made a small compat some times ago to be sure tombstone keeps the priority.

**Comment by vadis365** [comment]
It does exist- just nobody seems to be able to read the config.
It has been in the mod since we added the feature in 1.7.10, but people never look in the config
B:"Block O' Bones Inventory Save"=true
just turn that to false
May need a restart - it will turn the compass and the grave off
